---
abstract: 'Mojolicious plugin modular development.'
author:
  - 'Georgy Bazhukov <gosha@bugov.net>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4202, CPAN::Meta::Converter version 2.120351'
keywords:
  - Plugin
  - Module
  - Mojolicious
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Module
provides:
  Mojolicious::Plugin::Module:
    file: lib/Mojolicious/Plugin/Module.pm
    version: 0.01
  Mojolicious::Plugin::Module::Abstract:
    file: lib/Mojolicious/Plugin/Module/Abstract.pm
    version: 0
  Mojolicious::Plugin::Module::Manager:
    file: lib/Mojolicious/Plugin/Module/Manager.pm
    version: 0
requires:
  Carp: 0
  Hash::Merge::Simple: 0.051
  Module::Load: 0
  Mojolicious: 4
  perl: 5.014
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/bugov/mojolicious-plugin-module
version: 0.01
